dist: xenial
language: java
jdk:
  - openjdk8
  - openjdk11
  - openjdk-ea

matrix:
  allow_failures:
    - jdk: openjdk-ea

services:
  - xvfb

before_install:
  - git clone -b v3.0.0 --single-branch --depth=1 https://github.com/jdemetra/jdemetra-core.git ~/builds/jdemetra-core
  - pushd ~/builds/jdemetra-core
  - mvn clean install -DskipTests=true
  - popd

cache:
  directories:
    - $HOME/.m2
