language: java
jdk:
  - oraclejdk8

before_install:
  - git clone -b v3.0.0 --single-branch --depth=1 https://github.com/jdemetra/jdemetra-core.git ~/builds/jdemetra-core
  - pushd ~/builds/jdemetra-core
  - mvn clean install -DskipTests=true
  - popd
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

cache:
  directories:
    - $HOME/.m2

deploy:
  # SNAPSHOTS from develop & jdk8
  - provider: script
    script: mvn deploy -Dmaven.test.skip -s .travis.settings.xml -P deploy-snapshots
    skip_cleanup: true
    on:
      branch: develop
      jdk: oraclejdk8
      condition: $TRAVIS_PULL_REQUEST = "false"
      
  # RELEASES from master & jdk8
  - provider: script
    script: mvn deploy -Dmaven.test.skip -s .travis.settings.xml -P deploy-releases
    skip_cleanup: true
    on:
      branch: master
      jdk: oraclejdk8
      condition: $TRAVIS_PULL_REQUEST = "false"
